name: ArkPreparationDaily

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: '30 21 * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: PreparationDaily
      env:
        COOKIES: ${{ secrets.COOKIES }}
        SC_KEY: ${{ secrets.SC_KEY }}
      run: |
        python main.py
